/**
  * 套利相关错误码, 值必须在4000-5000之间
  */
namespace * xueqiao.trade.hosting.arbitrage.thriftapi

enum TradeHostingArbitrageErrorCode {
    ERROR_XQ_ORDER_ID_FORMAT = 4000,  // 雪橇订单ID格式不正确
    ERROR_XQ_ORDER_TYPE_NOT_SUPPORTED = 4001,  // 雪橇订单类型不支持
    ERROR_XQ_ORDER_NOT_EXISTS = 4002,  // 雪橇订单不存在
    ERROR_XQ_ORDER_EXISTED = 4003,  // 雪橇订单已经存在
    ERROR_XQ_ORDER_EFFECT_DATE_TYPE_NOT_SUPPORTED = 4004, // 不支持的有效期类型
    ERROR_XQ_ORDER_PARAM_ILLEGAL_TO_SYSTEM_SETTINGS = 4005, // 订单参数超过系统限制无效
    
    ERROR_XQ_ORDER_TRADETIME_CONSTRUCT_FAILED = 4100,  // 构建交易时间段失败
    ERROR_XQ_ORDER_TRADETIME_NO_RECENT = 4101,  // 最近无任何交易时间
    
    // 功能性暂停的原因
    ERROR_XQ_ORDER_SUSPENDED_NOTIN_TRADETIME = 4150, // 不在交易时间段
    ERROR_XQ_ORDER_SUSPENDED_BEFORE_EFFECT_TIME_PERIOD = 4151, // 订单还未生效
    
    // 异常暂停的原因
    ERROR_XQ_ORDER_SUSPENDED_LEG_ORDER_VERIFY_FAILED = 4199, // 腿订单审核失败
    ERROR_XQ_ORDER_SUSPENDED_LEG_ORDER_SEND_FAILED = 4200, // 腿订单发送失败
    ERROR_XQ_ORDER_SUSPENDED_LEG_ORDER_CANCELLED_TOO_MANY = 4201, // 腿撤单次数过多, 超过限制
    ERROR_XQ_ORDER_SUSPENDED_LEG_ORDER_PRICE_PROTECTED = 4202,  // 腿触发追价保护，导致暂停
    ERROR_XQ_ORDER_SUSPENDED_LEG_LEAK_BUT_TRADE_CLOSE = 4203, // 瘸腿但是市场停止交易
    ERROR_XQ_ORDER_SUSPENDED_INNER_STATE_ERROR = 4204,  // 内部状态异常导致暂停
    ERROR_XQ_ORDER_SUSPENDED_INNER_EXCEPTION_OCCURS = 4205,  // 内部异常导致暂停
    ERROR_XQ_ORDER_SUSPENDED_OPERATION_INTENT_UNKOWN = 4206,  // 操作意图不明确
    ERROR_XQ_ORDER_SUSPENDED_EXEC_ORDER_VERIFY_FAILED = 4207, // 执行订单审核失败，导致订单暂停
    ERROR_XQ_ORDER_SUSPENDED_EXEC_ORDER_SEND_FAILED = 4208,  // 执行订单发送失败，导致订单暂停
    ERROR_XQ_ORDER_SUSPENDED_EXEC_ORDER_UPSIDE_REJECTED = 4209, // 执行订单上手拒绝， 导致订单暂停
    ERROR_XQ_ORDER_SUSPENDED_EXEC_ORDER_UPSIDE_CANCELLED = 4210, // 执行订单上手撤单，导致订单暂停
    ERROR_XQ_ORDER_SUSPENDED_EXEC_ORDER_UPSIDE_EXPIRED = 4211,  // 执行订单过期，导致订单暂停
    
    
    // 操作失败的原因
    ERROR_XQ_ORDER_TYPE_SUSPEND_NOT_SUPPORTED = 4600,  // 雪橇订单类型不支持暂停
    ERROR_XQ_ORDER_STATE_CANNOT_OPERATION = 4601,  // 雪橇订单状态不支持此项操作
    ERROR_XQ_ORDER_NOT_EFFECTIVE_CANNOT_OPERATION = 4602,   // 订单非活跃，不可操作
    
    // 导致撤单的原因
    ERROR_XQ_ORDER_CANCELLED_STARTED_BUT_AFTER_EFFECT_TIME_PERIOD = 4698, // 订单已过有效期，触发启动时撤单
    ERROR_XQ_ORDER_CANCELLED_AFTER_EFFECT_TIME_PERIOD = 4699, // 订单过期，导致订单撤销
    ERROR_XQ_ORDER_CANCELLED_BY_USER = 4700,  // 用户撤销订单
    ERROR_XQ_ORDER_CANCELLED_EXEC_ORDER_VERIFY_FAILED = 4701, // 执行订单审核失败，导致订单撤销
    ERROR_XQ_ORDER_CANCELLED_EXEC_ORDER_SEND_FAILED = 4702,  // 执行订单发送失败，导致订单撤销
    ERROR_XQ_ORDER_CANCELLED_EXEC_ORDER_UPSIDE_REJECTED = 4703, // 执行订单上手拒绝， 导致订单撤销
    ERROR_XQ_ORDER_CANCELLED_EXEC_ORDER_UPSIDE_CANCELLED = 4704, // 执行订单上手撤单，导致订单撤销
    ERROR_XQ_ORDER_CANCELLED_MARKET_CLOSED = 4707,  // 已经闭市，当日有效订单不可交易
    ERROR_XQ_ORDER_CANCELLED_ANALYSIS_TRADETIME_FAILED = 4708, // 分析交易时间失败
    ERROR_XQ_ORDER_CANCELLED_MARKET_OPENDED_FOR_PARKED = 4709, // 开市阶段，预埋单无效
    ERROR_XQ_ORDER_CANCELLED_STARTING_TOO_LONG_FOR_PARKED = 4710, // 系统异常导致启动时间过久
    ERROR_XQ_ORDER_CANCELLED_TRIGGER_RUNNING_TOO_LONG_FOR_PARKED = 4711, // 预埋单触发器运行时间过长
    ERROR_XQ_ORDER_CANCELLED_COMPOSE_EXEC_TYPE_NOT_SUPPORTED = 4712,  // 不支持的组合执行类型
    ERROR_XQ_ORDER_CANCELLED_COMPOSE_NO_ACCEPTABLE_FIRSTLEG = 4713,  // 组合无可用先手腿
    ERROR_XQ_ORDER_CANCELLED_INNER_EXCEPTION_OCCURS = 4714,  // 内部异常导致撤单
    
}